### ISSUE TITLE
Add plotly dependences in foam_ui package.json. 

### ISSUE THREAD

**Issue by VasilisaPrikhodko** [jejomath/foam#10]
Hello, 
We would like to use your foam project. We followed the ReadMe to setup the project and realized the small fix is needed:  

- To maintain 1-step deploying of foam UI, it was suggested to add dependencies due to avoid a compilation error in FigurePage "can't resolve react-ploty.js". This dependences are located in test_data/package.json.

```
"plotly.js": "^2.18.1",
"react-plotly.js": "^2.6.0"
```

Thank you!

**Comment by jejomath** [comment]
I'm glad to hear you'd like to use this project! I added those to package.json - If it works now, please let me know. I'll leave the issue open until you confirm that it works. Thanks!

**Comment by VasilisaPrikhodko** [comment]
I tried installing the project from a branch: jejomath-patch-1 and it went smoothly. 
I can confirm that it has been resolved. Thank you!
